name: 💡 Feature request
description: Suggest a new feature or enhancement
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this useful or important?
